CREATE TABLE "otp" (
    "id" bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "code" VARCHAR(6) NOT NULL,
    "used" BOOLEAN DEFAULT FALSE,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    "expired_at" TIMESTAMP WITH TIME ZONE DEFAULT (NOW() + INTERVAL '5 minutes') NOT NULL
);